/**
 * Canonical platform slugs based on Daijishou platform definitions.
 * Legacy aliases are kept at the end so existing scrapers continue to work.
 */

const CONSOLES = {
  THREE_DO: "3do",
  AMSTRAD_CPC: "cpc",
  APPLE_II: "appleii",
  ARCADE_FINALBURN_NEO: "fbneo",
  ARCADE_MAME: "mame",
  ARCADIA_2001: "arcadia",
  ARDUBOY: "arduboy",
  ATARI_2600: "atari2600",
  ATARI_5200: "atari5200",
  ATARI_7800: "atari7800",
  ATARI_JAGUAR: "jaguar",
  ATARI_JAGUAR_CD: "jaguarcd",
  ATARI_LYNX: "lynx",
  ATARI_ST: "atarist",
  ATOMISWAVE: "atomiswave",
  ACORN_BBC_MICRO: "bbcmicro",
  BOOK_READER: "ebook",
  CPS_1: "cps1",
  CPS_2: "cps2",
  CPS_3: "cps3",
  CANNONBALL_OUTRUN_ENGINE: "cannonball",
  CAVE_STORY_GAME_ENGINE: "cavestory",
  CHIP_8: "chip8",
  COLECOVISION: "coleco",
  COMMODORE_64: "c64",
  COMMODORE_AMIGA: "amiga",
  COMMODORE_PET: "pet",
  COMMODORE_PLUS_4: "plus4",
  DOOM_GAME_ENGINE: "doom",
  DOS: "dos",
  DREAMCAST: "dreamcast",
  ELEKTOR_TV_GAMES_COMPUTER: "elektor",
  FAIRCHILD_CHANNEL_F: "channelf",
  FAMICOM_DISK_SYSTEM: "fds",
  FLASHBACK_GAME_ENGINE: "flashback",
  IDTECH4A: "idtech",
  INTELLIVISION: "intellivision",
  INTERTON_VC_4000: "vc4000",
  JAVA_ME: "j2me",
  LOWRES_NX: "lowresnx",
  MSX: "msx",
  MAGNAVOX_ODYSSEY_2: "odyssey2",
  MEGA_DUCK: "megaduck",
  MICROSOFT_XBOX: "xbox",
  MICROSOFT_XBOX_360: "xbox360",
  MOONLIGHT_STREAMING: "moonlight",
  NEC_PC_88: "pc88",
  NEC_PC_98: "pc98",
  NEC_PC_FX: "pcfx",
  NEO_GEO: "neogeo",
  NEO_GEO_CD: "neogeocd",
  NEO_GEO_POCKET: "ngp",
  NEO_GEO_POCKET_COLOR: "ngpc",
  NOKIA_N_GAGE: "ngage",
  NINTENDO_3DS: "3ds",
  NINTENDO_64: "n64",
  NINTENDO_DS: "nds",
  NINTENDO_DSI: "ndsi",
  NINTENDO_NES: "nes",
  NINTENDO_GAME_AND_WATCH: "gw",
  NINTENDO_GAME_BOY: "gb",
  NINTENDO_GAME_BOY_ADVANCE: "gba",
  NINTENDO_GAME_BOY_COLOR: "gbc",
  NINTENDO_GAMECUBE: "gc",
  NINTENDO_SATELLAVIEW: "satellaview",
  NINTENDO_SWITCH: "switch",
  NINTENDO_WII: "wii",
  NINTENDO_WII_U: "wiiu",
  NINTENDO_WIIWARE: "wiiware",
  PICO_8: "pico8",
  PALM_OS: "palm",
  PHILIPS_CD_I: "cdi",
  PHILIPS_VIDEOPAC_G7400: "g7400",
  SONY_PSP: "psp",
  SONY_PSP_MINIS: "pspminis",
  POKEMON_MINI: "pokemini",
  QUAKE_GAME_ENGINE: "quake",
  QUAKE_II_GAME_ENGINE: "quake2",
  RPG_MAKER: "rpgmaker",
  SCUMMVM: "scummvm",
  SEGA_32X: "sega32x",
  SEGA_CD: "segacd",
  SEGA_GAME_GEAR: "gamegear",
  SEGA_GENESIS: "genesis",
  SEGA_GENESIS_MSU: "genesismsu",
  SEGA_MASTER_SYSTEM: "master",
  SEGA_MODEL_3: "model3",
  SEGA_NAOMI: "naomi",
  SEGA_PICO: "pico",
  SEGA_SG_1000: "sg1000",
  SEGA_SATURN: "saturn",
  SHARP_X1: "x1",
  SHARP_X68000: "x68000",
  SONY_PLAYSTATION_VITA: "vita",
  SONY_PLAYSTATION: "psx",
  SONY_PLAYSTATION_2: "ps2",
  SONY_PLAYSTATION_3: "ps3",
  STEAM: "steam",
  SUPERGRAFX: "supergrafx",
  NINTENDO_SNES: "snes",
  NINTENDO_SNES_MSU_1: "snesmsu1",
  TIC_80: "tic80",
  TRIFORCE: "triforce",
  TURBOGRAFX_16: "tg16",
  TURBOGRAFX_CD: "tgcd",
  UZEBOX: "uzebox",
  VIC_20: "vic20",
  VECTREX: "vectrex",
  VIDEO_PLAYER: "videos",
  NINTENDO_VIRTUAL_BOY: "virtualboy",
  WASM_4: "wasm4",
  WATARA_SUPERVISION: "supervision",
  WINDOWS: "windows",
  WONDERSWAN: "ws",
  WONDERSWAN_COLOR: "wsc",
  XBOX_GAME_PASS: "xcloud",
  ZX_81: "zx81",
  ZX_SPECTRUM: "zxspectrum",

  // Legacy aliases used by current codebase
  XBOX: "xbox",
  XBOX_360: "xbox360",
  SEGA_DREAMCAST: "dreamcast",
  NEC_PC_ENGINE: "tg16",
  NEC_PC_ENGINE_CD: "tgcd",
  NEC_SUPERGRAFX: "supergrafx",
  SNK_NEO_GEO: "neogeo",
  SNK_NEO_GEO_POCKET: "ngp",
  SNK_NEO_GEO_POCKET_COLOR: "ngpc",
  BANDAI_WONDERSWAN: "ws",
  BANDAI_WONDERSWAN_COLOR: "wsc",
  GCE_VECTREX: "vectrex",
};

const PLATFORM_NAME_TO_SLUG = {
  "3DO": CONSOLES.THREE_DO,
  "Amstrad CPC": CONSOLES.AMSTRAD_CPC,
  "Apple II": CONSOLES.APPLE_II,
  "Arcade (FinalBurn Neo)": CONSOLES.ARCADE_FINALBURN_NEO,
  "Arcade (MAME)": CONSOLES.ARCADE_MAME,
  "Arcadia 2001": CONSOLES.ARCADIA_2001,
  "Arduboy": CONSOLES.ARDUBOY,
  "Atari 2600": CONSOLES.ATARI_2600,
  "Atari 5200": CONSOLES.ATARI_5200,
  "Atari 7800": CONSOLES.ATARI_7800,
  "Atari Jaguar": CONSOLES.ATARI_JAGUAR,
  "Atari Jaguar CD": CONSOLES.ATARI_JAGUAR_CD,
  "Atari Lynx": CONSOLES.ATARI_LYNX,
  "Atari ST": CONSOLES.ATARI_ST,
  "Atomiswave": CONSOLES.ATOMISWAVE,
  "Acorn Computers BBC Micro": CONSOLES.ACORN_BBC_MICRO,
  "Book Reader": CONSOLES.BOOK_READER,
  "CP System I": CONSOLES.CPS_1,
  "CP System II": CONSOLES.CPS_2,
  "CP System III": CONSOLES.CPS_3,
  "Cannonball OutRun Engine": CONSOLES.CANNONBALL_OUTRUN_ENGINE,
  "Cave Story Game Engine": CONSOLES.CAVE_STORY_GAME_ENGINE,
  "CHIP-8": CONSOLES.CHIP_8,
  "ColecoVision": CONSOLES.COLECOVISION,
  "Commodore 64": CONSOLES.COMMODORE_64,
  "Commodore Amiga": CONSOLES.COMMODORE_AMIGA,
  "Commodore - PET": CONSOLES.COMMODORE_PET,
  "Commodore - PLUS/4": CONSOLES.COMMODORE_PLUS_4,
  "DOOM Game Engine": CONSOLES.DOOM_GAME_ENGINE,
  "DOS": CONSOLES.DOS,
  "Dreamcast": CONSOLES.DREAMCAST,
  "Elektor TV Games Computer": CONSOLES.ELEKTOR_TV_GAMES_COMPUTER,
  "Fairchild Channel F": CONSOLES.FAIRCHILD_CHANNEL_F,
  "Famicom Disk System": CONSOLES.FAMICOM_DISK_SYSTEM,
  "Flashback Game Engine": CONSOLES.FLASHBACK_GAME_ENGINE,
  "idTech4A++": CONSOLES.IDTECH4A,
  "Intellivision": CONSOLES.INTELLIVISION,
  "Interton VC 4000": CONSOLES.INTERTON_VC_4000,
  "Java Me": CONSOLES.JAVA_ME,
  "LowRes NX": CONSOLES.LOWRES_NX,
  "MSX": CONSOLES.MSX,
  "Magnavox Odyssey 2": CONSOLES.MAGNAVOX_ODYSSEY_2,
  "Mega Duck": CONSOLES.MEGA_DUCK,
  "Microsoft - Xbox": CONSOLES.MICROSOFT_XBOX,
  "Microsoft - XBox 360": CONSOLES.MICROSOFT_XBOX_360,
  "Moonlight Streaming": CONSOLES.MOONLIGHT_STREAMING,
  "NEC PC-88": CONSOLES.NEC_PC_88,
  "NEC PC-98": CONSOLES.NEC_PC_98,
  "NEC PC-FX": CONSOLES.NEC_PC_FX,
  "Neo Geo": CONSOLES.NEO_GEO,
  "Neo Geo CD": CONSOLES.NEO_GEO_CD,
  "NeoGeo Pocket": CONSOLES.NEO_GEO_POCKET,
  "NeoGeo Pocket Color": CONSOLES.NEO_GEO_POCKET_COLOR,
  "Nokia N-Gage": CONSOLES.NOKIA_N_GAGE,
  "Nintendo 3DS": CONSOLES.NINTENDO_3DS,
  "Nintendo 64": CONSOLES.NINTENDO_64,
  "Nintendo DS": CONSOLES.NINTENDO_DS,
  "Nintendo DSi": CONSOLES.NINTENDO_DSI,
  "Nintendo Entertainment System": CONSOLES.NINTENDO_NES,
  "Nintendo - Game & Watch": CONSOLES.NINTENDO_GAME_AND_WATCH,
  "Nintendo - Game Boy": CONSOLES.NINTENDO_GAME_BOY,
  "Nintendo - Game Boy Advance": CONSOLES.NINTENDO_GAME_BOY_ADVANCE,
  "Nintendo - Game Boy Color": CONSOLES.NINTENDO_GAME_BOY_COLOR,
  "Nintendo - GameCube": CONSOLES.NINTENDO_GAMECUBE,
  "Nintendo Satellaview": CONSOLES.NINTENDO_SATELLAVIEW,
  "Nintendo Switch": CONSOLES.NINTENDO_SWITCH,
  "Nintendo Wii": CONSOLES.NINTENDO_WII,
  "Nintendo Wii U": CONSOLES.NINTENDO_WII_U,
  "Nintendo WiiWare": CONSOLES.NINTENDO_WIIWARE,
  "PICO-8": CONSOLES.PICO_8,
  "Palm OS": CONSOLES.PALM_OS,
  "Philips CD-i": CONSOLES.PHILIPS_CD_I,
  "Philips Videopac+ G7400": CONSOLES.PHILIPS_VIDEOPAC_G7400,
  "PlayStation Portable": CONSOLES.SONY_PSP,
  "PlayStation Portable Minis": CONSOLES.SONY_PSP_MINIS,
  "Pokemon Mini": CONSOLES.POKEMON_MINI,
  "Quake Game Engine": CONSOLES.QUAKE_GAME_ENGINE,
  "Quake II Game Engine": CONSOLES.QUAKE_II_GAME_ENGINE,
  "RPG Maker": CONSOLES.RPG_MAKER,
  "ScummVM": CONSOLES.SCUMMVM,
  "Sega 32X": CONSOLES.SEGA_32X,
  "Sega CD": CONSOLES.SEGA_CD,
  "Sega Game Gear": CONSOLES.SEGA_GAME_GEAR,
  "Sega Genesis": CONSOLES.SEGA_GENESIS,
  "Sega Genesis - MSU": CONSOLES.SEGA_GENESIS_MSU,
  "Sega Master System": CONSOLES.SEGA_MASTER_SYSTEM,
  "Sega Model 3": CONSOLES.SEGA_MODEL_3,
  "Sega Naomi": CONSOLES.SEGA_NAOMI,
  "Sega Pico": CONSOLES.SEGA_PICO,
  "Sega SG-1000": CONSOLES.SEGA_SG_1000,
  "Sega Saturn": CONSOLES.SEGA_SATURN,
  "Sharp X1": CONSOLES.SHARP_X1,
  "Sharp X68000": CONSOLES.SHARP_X68000,
  "Sony PS Vita": CONSOLES.SONY_PLAYSTATION_VITA,
  "Sony PlayStation": CONSOLES.SONY_PLAYSTATION,
  "Sony PlayStation 2": CONSOLES.SONY_PLAYSTATION_2,
  "Sony PlayStation 3": CONSOLES.SONY_PLAYSTATION_3,
  "Steam": CONSOLES.STEAM,
  "SuperGrafx": CONSOLES.SUPERGRAFX,
  "Super Nintendo Entertainment System": CONSOLES.NINTENDO_SNES,
  "Super Nintendo Entertainment System - MSU-1": CONSOLES.NINTENDO_SNES_MSU_1,
  "TIC-80": CONSOLES.TIC_80,
  Triforce: CONSOLES.TRIFORCE,
  "TurboGrafx-16": CONSOLES.TURBOGRAFX_16,
  "TurboGrafx-CD": CONSOLES.TURBOGRAFX_CD,
  Uzebox: CONSOLES.UZEBOX,
  "VIC-20": CONSOLES.VIC_20,
  Vectrex: CONSOLES.VECTREX,
  "Video Player": CONSOLES.VIDEO_PLAYER,
  "Virtual Boy": CONSOLES.NINTENDO_VIRTUAL_BOY,
  "WASM-4": CONSOLES.WASM_4,
  "Watara Supervision": CONSOLES.WATARA_SUPERVISION,
  Windows: CONSOLES.WINDOWS,
  WonderSwan: CONSOLES.WONDERSWAN,
  "WonderSwan Color": CONSOLES.WONDERSWAN_COLOR,
  "XBox Game Pass": CONSOLES.XBOX_GAME_PASS,
  "ZX 81": CONSOLES.ZX_81,
  "ZX Spectrum": CONSOLES.ZX_SPECTRUM,
};

const LEGACY_SYSTEM_ALIASES = {
  "Nintendo - Nintendo Entertainment System": CONSOLES.NINTENDO_NES,
  "Nintendo - Super Nintendo Entertainment System": CONSOLES.NINTENDO_SNES,
  "Nintendo - Nintendo 64": CONSOLES.NINTENDO_64,
  "Nintendo - Wii": CONSOLES.NINTENDO_WII,
  "Nintendo - Wii U": CONSOLES.NINTENDO_WII_U,
  "Nintendo - Nintendo DS": CONSOLES.NINTENDO_DS,
  "Nintendo - Nintendo 3DS": CONSOLES.NINTENDO_3DS,
  "Nintendo - Virtual Boy": CONSOLES.NINTENDO_VIRTUAL_BOY,
  "Nintendo - Switch": CONSOLES.NINTENDO_SWITCH,

  "Sony - PlayStation": CONSOLES.SONY_PLAYSTATION,
  "Sony - PlayStation 2": CONSOLES.SONY_PLAYSTATION_2,
  "Sony - PlayStation 3": CONSOLES.SONY_PLAYSTATION_3,
  "Sony - PlayStation Portable": CONSOLES.SONY_PSP,
  "Sony - PlayStation Vita": CONSOLES.SONY_PLAYSTATION_VITA,

  "Sega - Master System": CONSOLES.SEGA_MASTER_SYSTEM,
  "Sega - Mega Drive - Genesis": CONSOLES.SEGA_GENESIS,
  "Sega - Sega CD": CONSOLES.SEGA_CD,
  "Sega - 32X": CONSOLES.SEGA_32X,
  "Sega - Saturn": CONSOLES.SEGA_SATURN,
  "Sega - Dreamcast": CONSOLES.DREAMCAST,
  "Sega - Game Gear": CONSOLES.SEGA_GAME_GEAR,

  "Atari - 2600": CONSOLES.ATARI_2600,
  "Atari - 5200": CONSOLES.ATARI_5200,
  "Atari - 7800": CONSOLES.ATARI_7800,
  "Atari - Jaguar": CONSOLES.ATARI_JAGUAR,
  "Atari - Lynx": CONSOLES.ATARI_LYNX,

  "NEC - PC Engine": CONSOLES.TURBOGRAFX_16,
  "NEC - PC Engine CD": CONSOLES.TURBOGRAFX_CD,
  "NEC - SuperGrafx": CONSOLES.SUPERGRAFX,

  "SNK - Neo Geo": CONSOLES.NEO_GEO,
  "SNK - Neo Geo Pocket": CONSOLES.NEO_GEO_POCKET,
  "SNK - Neo Geo Pocket Color": CONSOLES.NEO_GEO_POCKET_COLOR,

  "Commodore - 64": CONSOLES.COMMODORE_64,
  "Commodore - Amiga": CONSOLES.COMMODORE_AMIGA,
  "Bandai - WonderSwan": CONSOLES.WONDERSWAN,
  "Bandai - WonderSwan Color": CONSOLES.WONDERSWAN_COLOR,
  "GCE - Vectrex": CONSOLES.VECTREX,
  "Magnavox - Odyssey2": CONSOLES.MAGNAVOX_ODYSSEY_2,

  // Additional legacy slug aliases from previous versions
  ps1: CONSOLES.SONY_PLAYSTATION,
  psvita: CONSOLES.SONY_PLAYSTATION_VITA,
  sms: CONSOLES.SEGA_MASTER_SYSTEM,
  pce: CONSOLES.TURBOGRAFX_16,
  pcecd: CONSOLES.TURBOGRAFX_CD,
  vb: CONSOLES.NINTENDO_VIRTUAL_BOY,
  wonderswan: CONSOLES.WONDERSWAN,
  wonderswancolor: CONSOLES.WONDERSWAN_COLOR,
};

const CONSOLE_MAPPING = {
  ...PLATFORM_NAME_TO_SLUG,
  ...LEGACY_SYSTEM_ALIASES,
};

function getConsoleFromSystem(systemName) {
  return CONSOLE_MAPPING[systemName] || "unknown";
}

function getConsoleNameFromSlug(consoleSlug) {
  for (const [name, slug] of Object.entries(PLATFORM_NAME_TO_SLUG)) {
    if (slug === consoleSlug) {
      return name;
    }
  }
  for (const [name, slug] of Object.entries(LEGACY_SYSTEM_ALIASES)) {
    if (slug === consoleSlug) {
      return name;
    }
  }
  return "Unknown";
}

module.exports = {
  CONSOLE_MAPPING,
  CONSOLES,
  getConsoleFromSystem,
  getConsoleNameFromSlug,
};
